### PR TITLE
Prioritizes Download and Issue links

### PR DESCRIPTION
**Pull request by WillStrohl**

### CODE REVIEW

**Review by david-poindexter — COMMENTED** [review]
@hismightiness is this what you intended?

image

**Comment by WillStrohl** [comment]
Yes sir, it is.  The two most common actions are on the top.  :)

**Review by valadas — APPROVED** [review]
Looks good to me

**Review by david-poindexter — APPROVED** [review]
Awesome - thanks @hismightiness 🎉

**Pull request merged**
